apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-organization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-organization
  template:
    metadata:
      labels:
        app: ms-organization
    spec:
      containers:
      - name: ms-organization-container
        image: quay.io/j-martinez/meta-ms-organization
        ports:
        - containerPort: 3000
